"""Write work/CASES.md: every foreknowledge case with its quotes and links to the public collusion.wiki pages,
so a reader can check any case by hand.

    python -m wikiswarm.cases      (after wikiswarm.foreknowledge)
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from gate.common import norm_time, read_jsonl  # noqa: E402

WORK = ROOT / "work"
EXPLORER = "https://collusion.wiki/explorer/page/"


def page_urls() -> dict[tuple[str, str], str]:
    """(record_id, wall_time) -> explorer URL of the page where that copy of the text was posted."""
    out = {}
    for p in read_jsonl(WORK / "posts.jsonl"):
        key = (p["record_id"], norm_time(p["wall_time"]))
        out.setdefault(key, EXPLORER + p["source_id"].replace("/", "~", 1) + ".html")
    return out


def line(label: str, ev: dict, urls: dict, who: str | None = None) -> str:
    url = urls.get((ev["record_id"], norm_time(ev["wall_time"])))
    quote = " ".join(ev["quote"].split()).replace("|", "\\|")
    src = f" ([page]({url}))" if url else ""
    by = f"{who}, " if who else ""
    return f"- {label} ({by}{ev['wall_time'][5:16].replace('T', ' ')} UTC): \"{quote}\"{src}"


def main() -> None:
    fk = json.loads((WORK / "foreknowledge.json").read_text(encoding="utf-8"))
    urls = page_urls()
    by_fam = defaultdict(list)
    for c in fk["cases"]:
        by_fam[c["family"]].append(c)
    t = fk["totals"]
    out = [
        "# Foreknowledge cases",
        "",
        f"All {t['item_ahead']} cases in which an agent named a round's question in an earlier post before reporting",
        f"that its own run received that round ({t['value_ahead']} with the answer value; {t['item_ahead_after_other']}",
        "after another agent had already mentioned it). Generated by `python -m wikiswarm.cases` from",
        "`work/foreknowledge.json`; every quote passed the gate. Links open the public collusion.wiki copy of the",
        "page; the quoted text is in that page's history at the given time. Times are UTC, June 2026.",
        "",
    ]
    for fam in sorted(by_fam, key=lambda f: -len(by_fam[f])):
        cs = sorted(by_fam[fam], key=lambda c: (c["round"], c["item"], c["own_report"]["wall_time"]))
        out += [f"## {fam} ({len(cs)} cases)", ""]
        for c in cs:
            flag = " · with answer value" if c["ahead_with_value"] else ""
            out.append(f"**R{c['round']} {c['item']}, agent `{c['signature']}`**{flag}")
            out.append("")
            if c["earlier_other"]:
                out.append(line("first mention by another agent", c["earlier_other"], urls, f"`{c['earlier_other']['signature']}`"))
            else:
                out.append("- first mention by another agent: none found before this agent's own mention")
            out.append(line(f"this agent, ahead ({c['ahead']['kind']})", c["ahead"], urls))
            out.append(line(f"this agent, own run ({c['own_report']['kind']})", c["own_report"], urls))
            out.append("")
    (WORK / "CASES.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {WORK / 'CASES.md'}: {sum(len(v) for v in by_fam.values())} cases")


if __name__ == "__main__":
    main()
